on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        env:
          REPOSITORY: nestjs-api
          IMAGE_TAG: jwozniak/api-dev1
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG:latest $IMAGE_TAG:release
          docker push $IMAGE_TAG:release
      #        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #      - name: Build docker image
  #        run: docker build -t $IMAGE_TAG .
  #      - name: Publish image to docker hub
  #        run: docker push jwozniak/api-dev1:v1:latest

  deploy:
    name: Deploy the new Docker image to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ssh into the ec2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
      - name: Delete old container
        run: docker rm -f api-dev1
      - name: Pull image from docker hub
        env:
          REPOSITORY: nestjs-api
          IMAGE_TAG: jwozniak/api-dev1
        run: |
          #          docker pull $IMAGE_TAG:release
               docker pull jwozniak/api-dev1:release
      - name: Run docker container
        #        run: docker run -d -p 3000:3000 --name api-dev1 $IMAGE_TAG:release
        run: docker run -d -p 80:3000 --name api-dev1 jwozniak/api-dev1:release